spring:
  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      database: "GAME-DATA"
      host: localhost
      port: 27017
server:
  port: 8888

match:
  exchange: matches
  result:
    queue: result
    key: result