spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
  data:
    mongodb:
      database: "GAME-DATA"
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
server:
  port: 7777

match:
  exchange: matches
  result:
    queue: result
    key: result

logging:
  level:
    root: INFO